### ISSUE TITLE
Stories should be identified by FFNet IDs instead of full URLs

### ISSUE THREAD

**Issue by AndyScull** [MRH4287/FFNetParser#40] opened 2015-12-27 08:26 UTC
If I understand correctly, currently FFNetParser distinguish stories by full urls instead of FFNet ids.
This should be changed to parsing url and getting exact ffnet id, since all text in url after story id and chapter number is irrelevant to ffnet.
For example the same story could be refered by all these urls -
https://www.fanfiction.net/s/3946501/1/Thousand-Shinji
https://www.fanfiction.net/s/3946501/1/asd
https://www.fanfiction.net/s/3946501/1/
At some places and in few programs, people shorten urls and remove title text in the end of url. That breaks FFNetParser functionality since following these urls I see the story isn't categorized and try to reread it (story IS categorized in FFNetParser db but it's url is different from url I am browsing)
Also, if author of story ever decides to change story's title, FFNetParser would 'forget' this story's forever...

And since fixing it would require some kind of regexp or url parsing, it would be nice to have all chapter paged get detected as same story, so we could have category show up everywhere

**Comment by MRH4287** [comment] 2015-12-27 09:16
Hi.
If you are referring to the Marker, then you are correct.
Those settings are saved for every Stroy-Url.
This is because the Settings also distinguish between chapters.

As i was writing this, this was my intention.
Changing it to the Story-ID wouldn't be a problem, but you would loose the current control you have.

The problem is, that i don't want to "break" the feature for everyone that might use it the other way.
What i can do though, is adding a Config-Option to change it.
The switch from one option to the other would be permanent though.

**Comment by AndyScull** [comment] 2015-12-27 10:44
Permanent is OK, thanks
I didn't think it was intentionally programmed that way though, I don't understand why you'd want to categorize/mark single chapters in story. Separate comments for chapters to remember story events in case you'd want to reread it later are a possibility, but overall rating-like category? It's not that you would skip 'bad' chapters while reading, leaving out parts of scenario, right? The only case I can imagine is marking chapters with lime content, but that should be done with tag-like system, not categories

**Comment by MRH4287** [comment] 2015-12-27 11:18
Well, the point is that you can make your own categories.
And so, make it a Tag System.

The System gives you the freedom to do as you like.
But i'll see what i can do later the day.

Thanks for the feedback and thanks for using my script!

**Comment by MRH4287** [comment] 2015-12-27 13:51
Changes will be in the next update :)

**Closed** 2015-12-27 13:51 UTC

**Comment by AndyScull** [comment] 2015-12-27 15:33
Thanks :)
Just wanted to be clear on tag-system - I meant usual blog-wordpress-whatever tag system, where you can tag the story with multiple keywords. But anyway, even with this kind of system, tagging single chapters would be worthless, since there are no functionality to browse a list of tagged chapters, this only would be visible when you actually visit the chapter's page. And that is no different from text comment, and this is already covered by 'sticky notes'-type addons

**Comment by MRH4287** [comment] 2015-12-27 15:36
@AndyScull True.
By the way: Are you the user who posted those notes on the Chrome Web-Store?
If you are, then please use Github or my Feedback System in the future.

I don't get notifications for those :/

**Comment by MRH4287** [comment] 2015-12-27 15:48
@AndyScull i just uploaded Version 5.4.4

**Comment by AndyScull** [comment] 2015-12-27 16:01
Many thanks!
You made my day today by these two added options ('story id' and 'don't change width')
Also I hope you don't mind that I moved back to FF and use your script with greasemonkey. FF engine is just more pleasing to my eyes than Chrome and _feels_ faster

**Comment by MRH4287** [comment] 2015-12-27 16:28
@AndyScull No Problem :)
I have no problem with your Browser choice ^^
I support Firefox too :P

And yes, i added the black border in one of the Changesets i made :)
